name: Deploy to Personal Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy
        run: |
          fuser -k 8081/tcp || true
          cp build/libs/*.jar /home/ksh/ksh/Word/build/libs
          cp -r . /home/ksh/ksh/Word/code
          cd /home/ksh/ksh
          docker compose up -d --build